# numpy pratice session

In [1]:
# import this library in j.notebook
import numpy as np

# creating an array using numpy

In [2]:
# 1D array
food=np.array(["pakora", "samosa", "raita"])
food

array(['pakora', 'samosa', 'raita'], dtype='<U6')

In [3]:
price=np.array([5, 6, 3])
price

array([5, 6, 3])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
len(price)

3

In [8]:
# indexing
food[2]

'raita'

In [9]:
price[0:]

array([5, 6, 3])

In [10]:
price.mean()

4.666666666666667

In [11]:
# zeroes method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# empty
np.empty(6)
 

array([0., 0., 0., 0., 0., 0.])

In [14]:
# range
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [15]:
#specify
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [16]:
# specific interval
np.arange(2, 6,3)

array([2, 5])

In [17]:
# table of 5
np.arange(0,55,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [18]:
# line space
np.linspace(0,100, num=11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [19]:
#specify data type
np.ones(6, dtype=np.int64)

array([1, 1, 1, 1, 1, 1], dtype=int64)

In [20]:
np.ones(22, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1.])

# Array functions

In [21]:
import numpy as np
a=np.array([22,12,34,3,5,6,6.6])
a

array([22. , 12. , 34. ,  3. ,  5. ,  6. ,  6.6])

In [22]:
a.sort()
a

array([ 3. ,  5. ,  6. ,  6.6, 12. , 22. , 34. ])

In [23]:
b=np.array([44,65,4.6,554])
b

array([ 44. ,  65. ,   4.6, 554. ])

In [24]:
c=np.concatenate((a,b))
c

array([  3. ,   5. ,   6. ,   6.6,  12. ,  22. ,  34. ,  44. ,  65. ,
         4.6, 554. ])

In [25]:
c.sort()
c

array([  3. ,   4.6,   5. ,   6. ,   6.6,  12. ,  22. ,  34. ,  44. ,
        65. , 554. ])

# 2-D array

In [26]:
a=np.array([[1,2,4,5,3],[2,4,5,4,1]])
a

array([[1, 2, 4, 5, 3],
       [2, 4, 5, 4, 1]])

In [27]:
b=np.array([[4,6,3,3,1],[4,6,4,3,2]])
b

array([[4, 6, 3, 3, 1],
       [4, 6, 4, 3, 2]])

In [28]:
c=np.concatenate((a,b))
c

array([[1, 2, 4, 5, 3],
       [2, 4, 5, 4, 1],
       [4, 6, 3, 3, 1],
       [4, 6, 4, 3, 2]])

In [29]:
c=np.concatenate((a,b), axis=0)
c

array([[1, 2, 4, 5, 3],
       [2, 4, 5, 4, 1],
       [4, 6, 3, 3, 1],
       [4, 6, 4, 3, 2]])

In [30]:
c=np.concatenate((a,b), axis=1)
c

array([[1, 2, 4, 5, 3, 4, 6, 3, 3, 1],
       [2, 4, 5, 4, 1, 4, 6, 4, 3, 2]])

# 3-D Array/tensor

In [31]:
a=np.array([[[2,3,4,4],
             [4,6,4,3]],
             
            [[4,6,4,2],
             [2,4,1,1]],
            
            [[3,3,3,3],
             [2,2,2,2]]])
a

array([[[2, 3, 4, 4],
        [4, 6, 4, 3]],

       [[4, 6, 4, 2],
        [2, 4, 1, 1]],

       [[3, 3, 3, 3],
        [2, 2, 2, 2]]])

In [32]:
a.ndim

3

In [33]:
type(a)

numpy.ndarray

In [34]:
b=np.array([[2,3,4,4],
             [4,6,4,3],
             
            [4,6,4,2],
             [2,4,1,1]])
b

array([[2, 3, 4, 4],
       [4, 6, 4, 3],
       [4, 6, 4, 2],
       [2, 4, 1, 1]])

In [35]:
b.ndim

2

In [36]:
c=np.array([[3,5,4],[4,3,2],[5,6,2]])
c

array([[3, 5, 4],
       [4, 3, 2],
       [5, 6, 2]])

In [37]:
c.ndim

2

In [38]:
# size means number of elements
a.size

24

In [40]:
a

array([[[2, 3, 4, 4],
        [4, 6, 4, 3]],

       [[4, 6, 4, 2],
        [2, 4, 1, 1]],

       [[3, 3, 3, 3],
        [2, 2, 2, 2]]])

In [41]:
# shape
a.shape

(3, 2, 4)

In [43]:
a=np.arange(9)#3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [44]:
# reshape
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
#reshape
np.reshape(a, newshape=(1, 9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [48]:
# convert 1D into 2D
a=np.array([1,2,3,4,5,6,5,4,3])
a

array([1, 2, 3, 4, 5, 6, 5, 4, 3])

In [49]:
a.shape

(9,)

In [50]:
#row wise 2d conversion
b=a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 5, 4, 3]])

In [51]:
b.shape

(1, 9)

In [52]:
#column wise
c=a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [5],
       [4],
       [3]])

In [53]:
a

array([1, 2, 3, 4, 5, 6, 5, 4, 3])

In [55]:
a[4:6]

array([5, 6])

In [56]:
a*5

array([ 5, 10, 15, 20, 25, 30, 25, 20, 15])

In [57]:
a+5

array([ 6,  7,  8,  9, 10, 11, 10,  9,  8])

In [59]:
a.sum()

33

In [60]:
a.mean()

3.6666666666666665

In [61]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
a[a<6]

array([1, 2, 3, 4, 5])

In [63]:
a[a>=6]

array([ 6,  7,  8,  9, 10, 11, 12])

In [64]:
#divisiable by 2
d=a[a%2==0]
d

array([ 2,  4,  6,  8, 10, 12])